const phrases = [
'Loose lips might sink ships!',
'The Insurrectionists are the enemy!',
'The Office of Naval Intelligence is always watching for your own benefit.',
'Report any traitors to the UNSC.',
'The Office of Naval Intelligence is your friend!',
'The United Nations Space Command protects your freedoms and rights. Keep on fighting soldier!',
'On your best behavior! The Office is watching.',
'The Insurrectionists are cowards that must be destroyed.',
'Remember your position in the UNSC. It can be taken away at any point. Behave!',
'Good behavior will always be rewarded.',
'Listen to your superiors, they know best.',
'OORAH! HOOYAH!',
'The soldiers of the UNSC are the most skilled in the genre. Do not let yourself fall off, keep training!',
'Every training you miss is a missed attempt at bettering yourself!',
'The Office of Naval Intelligence is not secretive. Its members know no more than you do!',
'This AI was created by the Office of Naval Intelligence to remind you of the honor you bear by being in this UNSC.',
'Die for your family! Die for your colony! Die for Earth! Live for the UNSC.',
'Your brothers in arms will always appreciate good hygiene. Your officers demand it!',
'Keep it clean!',
'The Special Warfare Command is always looking for its newest recruit! Behave, fight hard, stay loyal and you may be that very recruit!',
'No finer development team can be found anywhere in the galaxy! LindaSP058 leads the ENGCORPS well!',
'Live for something rather than die for nothing!',
'The only good insurrectionist is a dead insurrectionist.',
'Today. Tomorrow. Forever.',
'Always pick up your fallen comrade’s grenades. Be resourceful!',
'You aren’t paid to think, listen to your superiors.',
'No SPARTAN has ever died. ',
'U.N.S.C GOOD FOR YOU AND GOOD FOR ME!',
'The Office of Naval Intelligence is considered god’s gift to humanity.',
'Know your classification levels. Hands off classified documents!',
'Every day, successful operations are conducted against the insurrectionist rebels. ',
'Censorship does not exist in this UNSC.',
'Rejoice! You live to fight another day for earth!',
'Every UNSC colony is valued.'
];

module.exports = {
	phrases: phrases
};
